// Generated by Rec Studio 4 - build Sep 23 2015

_init()
{// addr = 0x080483C4
    _unknown_ __ebx;                       // r1
    _unknown_ _t5;                         // _t5

    L1();
    _pop(__ebx);
    if( *((intOrPtr*)(_t5 + 5727 - 4)) != 0) {
        __gmon_start__();
    }
    frame_dummy();
    return __do_global_ctors_aux();
}

L080483CD()
{
    _unknown_ _t4;                         // _t4
    _unknown_ _t5;                         // _t5

    _pop(__ebx);
    if( *((intOrPtr*)(_t5 + 5727 - 4)) != 0) {
        __gmon_start__();
    }
    frame_dummy();
    _t4 = __do_global_ctors_aux();
    __esp = __esp + 8;
    _pop(__ebx);
    return _t4;
}

printf()
{// addr = 0x08048410
    goto __imp__printf;
}

free()
{// addr = 0x08048420
    goto __imp__free;
}

strdup()
{// addr = 0x08048430
    goto __imp__strdup;
}

fgets()
{// addr = 0x08048440
    goto __imp__fgets;
}

fwrite()
{// addr = 0x08048450
    goto __imp__fwrite;
}

strcpy()
{// addr = 0x08048460
    goto __imp__strcpy;
}

malloc()
{// addr = 0x08048470
    goto __imp__malloc;
}

system()
{// addr = 0x08048480
    goto __imp__system;
}

__gmon_start__()
{// addr = 0x08048490
    goto __imp____gmon_start__;
}

__libc_start_main()
{// addr = 0x080484A0
    goto __imp____libc_start_main;
}

_start(
    signed int __eax,                      // r0
    _unknown_ __edx                        // r3
)
{// addr = 0x080484B0
    _unknown_ __ebx;                       // r1
    signed int _t4;                        // _t4
    signed int _t5;                        // _t5

    __edx = __edx;
    _t3 = __eax;
    _pop(__esi);
    __ecx = __esp;
    __esp = __esp & -16;
    _push(__eax);
    _push(__esp);
    _push(__edx);
    _push(__libc_csu_fini);
    _push(__libc_csu_init);
    _push(__ecx);
    _push(__esi);
    _push(main);
    __libc_start_main();
    asm("hlt");
    0;
    0;
    _push(0);
    _push(_t5);
    __esp = __esp - 4;
    if(completed.6159 == 0) {
        _t3 = dtor_idx.6161;
        _t5 = ( &__DTOR_END__ -  &__DTOR_LIST__ >> 2) - 1;
        if(_t3 <  &__DTOR_END__) {
            do {
                _t4 = _t3 + 1;
                dtor_idx.6161 = _t4;
                 *((intOrPtr*)(_t4 * 4 +  &__DTOR_LIST__))();
                _t3 = dtor_idx.6161;
            } while(_t3 < _t5);
        }
        completed.6159 = 1;
    }
    __esp = __esp + 4;
    _pop(__ebx);
    _pop(__ebp);
}

__do_global_dtors_aux()
{// addr = 0x080484E0
    _unknown_ __ebx;                       // r1
    _unknown_ _t3;                         // _t3
    signed int _t4;                        // _t4
    signed int _t5;                        // _t5
    signed int _t9;                        // _t9

    if(completed.6159 == 0) {
        _t4 = dtor_idx.6161;
        _t9 = ( &__DTOR_END__ -  &__DTOR_LIST__ >> 2) - 1;
        if(_t4 >=  &__DTOR_END__) {
L4:
            completed.6159 = 1;
            return;
        }
        do {
            _t5 = _t4 + 1;
            dtor_idx.6161 = _t5;
             *((intOrPtr*)(_t5 * 4 +  &__DTOR_LIST__))();
            _t4 = dtor_idx.6161;
        } while(_t4 < _t9);
        goto L4;
    }
}

frame_dummy()
{// addr = 0x08048540
    if(__JCR_LIST__ == 0 || 0 == 0) {
        return;
    } else {
         *__esp =  &__JCR_LIST__;
         *0();
        return;
    }
}

main()
{// addr = 0x08048564
    char _v12;                             // _cfa_fffffff4
    char _v140;                            // _cfa_ffffff74
    signed int _v144;                      // _cfa_ffffff70
    intOrPtr _v160;                        // _cfa_ffffff60
    intOrPtr _v164;                        // _cfa_ffffff5c
    intOrPtr* _v168;                       // _cfa_ffffff58
    _unknown_ __edi;                       // r4
    _unknown_ __esi;                       // r5
    intOrPtr _t30;                         // _t30
    intOrPtr _t51;                         // _t51
    char* _t97;                            // _t97
    _unknown_ _t99;                        // _t99
    _unknown_ _t100;                       // _t100
    intOrPtr _t102;                        // _t102

    __esp = __esp & -16;
    __esp = __esp - 160;
    while(1) {
        _v164 = service;
        _v168 = auth;
         *__esp = "%p, %p \n";
        printf();
        _v164 = __imp__stdin;
        _v168 = 128;
         *__esp =  &_v140;
        fgets();
        _t97 =  &_v140;
        if(_t97 == 0) {
            break;
        }
        asm("repe cmpsb");
        _t30 = (_t97 > 0) - (_t97 > 0);
        if(_t30 == 0) {
             *__esp = 4;
            malloc();
            auth = _t30;
             *auth = 0;
            _v144 = -1;
            asm("repne scasb");
            _t99 =  !_v144 - 1 - 30;
            if(_t99 <= 0) {
                _v168 =  &_v140 + 5;
                 *__esp = auth;
                strcpy();
            }
        }
        asm("repe cmpsb");
        _t100 = (_t99 > 0) - (_t99 > 0);
        if(_t100 == 0) {
             *__esp = auth;
            free();
        }
        asm("repe cmpsb");
        if(_t100 > 0 == _t100 > 0) {
            _t51 =  &_v140 + 7;
            _t102 = _t51;
             *__esp = _t51;
            strdup();
            service = _t51;
        }
        asm("repe cmpsb");
        if(_t102 > 0 == _t102 > 0) {
            if( *((intOrPtr*)(auth + 32)) == 0) {
                _v160 = __imp__stdout;
                _v164 = 10;
                _v168 = 1;
                 *__esp = "Password:\n";
                fwrite();
            } else {
                 *__esp = "/bin/sh";
                system();
            }
        }
    }
    __esp =  &_v12;
    return 0;
}

__libc_csu_init(
    intOrPtr _a4,                          // _cfa_4
    intOrPtr _a8,                          // _cfa_8
    intOrPtr _a12                          // _cfa_c
)
{// addr = 0x08048740
    intOrPtr _v36;                         // _cfa_ffffffdc
    intOrPtr _v40;                         // _cfa_ffffffd8
    _unknown_ __ebx;                       // r1
    _unknown_ __edi;                       // r4
    signed int __esi;                      // r5
    intOrPtr __ebp;                        // r6
    _unknown_ _t11;                        // _t11
    _unknown_ _t16;                        // _t16
    _unknown_ _t17;                        // _t17
    signed int _t20;                       // _t20

    __i686.get_pc_thunk.bx(_t11);
    _t17 = _t16 + 4835;
    __esp = __esp - 28;
    __ebp = _a4;
    _init();
    _t20 = _t17 - 224 - _t17 - 224 >> 2;
    if(_t20 != 0) {
        __esi = 0;
        do {
             *__esp = __ebp;
            _v36 = _a12;
            _v40 = _a8;
             *((intOrPtr*)(_t17 + __esi * 4 - 224))();
            __esi = __esi + 1;
        } while(__esi != _t20);
    }
    __esp = __esp + 28;
}

__libc_csu_fini(
    _unknown_ __eax                        // r0
)
{// addr = 0x080487B0
    __eax = __eax;
    asm("repe ret");
    return __eax;
}

__i686.get_pc_thunk.bx(
    _unknown_ __eax                        // r0
)
{// addr = 0x080487B2
    __eax = __eax;
    return __eax;
}

__do_global_ctors_aux()
{// addr = 0x080487C0
    intOrPtr* __ebx;                       // r1

    __eax = __CTOR_LIST__;
    if(__eax != -1) {
        __ebx =  &__CTOR_LIST__;
        do {
            __ebx = __ebx - 4;
             *__eax();
            __eax =  *__ebx;
        } while(__eax != -1);
    }
}

_fini()
{// addr = 0x080487EC
    _unknown_ __ebx;                       // r1
    _unknown_ _t1;                         // _t1

    L1();
    _pop(__ebx);
    return __do_global_dtors_aux();
}

L080487F5()
{
    _unknown_ _t1;                         // _t1

    _pop(__ebx);
    __eax = __do_global_dtors_aux();
    __esp = __esp + 8;
    _pop(__ebx);
    return __eax;
}

L080487F5()
{
    _unknown_ _t1;                         // _t1

    _pop(__ebx);
    __eax = @rec __do_global_dtors_aux@__do_global_dtors_aux@();
    __esp = __esp + 8;
    _pop(__ebx);
    return __eax;
}

// Statistics:
//      72 Register nodes
//      57 Temporaries nodes
//       6 Casts
//      76 Statements
//       2 Labels
//       1 Gotos
//      22 Blocks
//     552 Nodes
//       7 Assembly nodes
//      22 Unknown Types


Total time: 0 seconds.
