// tmp0vrim1_3_text.c
// Generated by decompiling tmp0vrim1_3
// using Reko decompiler version 0.11.6.0.

#include "tmp0vrim1_3.h"

// 080484B0: void _start(Register (ptr32 Eq_15) edx, Stack int32 dwArg00, Stack (ptr32 char) ptrArg04)
void _start(void (* edx)(), int32 dwArg00, char * ptrArg04)
{
	__align_stack<word32>(&ptrArg04);
	void * fp;
	__libc_start_main(&g_t8048564, dwArg00, &ptrArg04, &g_t8048740, &g_t80487B0, edx, fp);
	__halt();
}

// 080484E0: void __do_global_dtors_aux()
// Called from:
//      _fini
void __do_global_dtors_aux()
{
	if (g_b8049AA4 == 0x00)
	{
		uint32 eax_14 = dtor_idx.6161;
		while (eax_14 < 0x00)
		{
			uint32 eax_24 = eax_14 + 0x01;
			dtor_idx.6161 = eax_24;
			(*((char *) g_a8049954 + eax_24 * 0x04))();
			eax_14 = dtor_idx.6161;
		}
		g_b8049AA4 = 0x01;
	}
}

// 08048540: void frame_dummy()
// Called from:
//      _init
void frame_dummy()
{
	if (g_dw804995C != 0x00 && false)
		fn00000000(0x0804995C);
}

// 08048564: void main()
void main()
{
	char bLoc87;
	ptr32 fp;
	__align_stack<word32>(fp - 0x0C);
	while (true)
	{
		printf("%p, %p \n", auth, service);
		word32 dwLoc8C;
		if (fgets(&dwLoc8C, 0x80, stdin) == null)
			break;
		Eq_109 cmpResult_50 = memcmp(&dwLoc8C, &g_t8048819, 0x05);
		if ((int32) ((cmpResult_50 > 0x00) - (cmpResult_50 < 0x00)) == 0x00)
		{
			auth = malloc(0x04);
			auth->b0000 = (char) 0x00;
			uint32 eax_88 = strlen(&bLoc87) - ~0x00;
			if (eax_88 <= 0x1F && eax_88 >= 0x01)
				strcpy(auth, &bLoc87);
		}
		Eq_127 cmpResult_105 = memcmp(&dwLoc8C, &g_t804881F, 0x05);
		if ((int32) ((cmpResult_105 > 0x00) - (cmpResult_105 < 0x00)) == 0x00)
			free(auth);
		Eq_177 cmpResult_138 = memcmp(&dwLoc8C, &g_t8048825, 0x06);
		if ((int32) ((cmpResult_138 > 0x00) - (cmpResult_138 < 0x00)) == 0x00)
		{
			char bLoc85;
			service = strdup(&bLoc85);
		}
		Eq_200 cmpResult_174 = memcmp(&dwLoc8C, &g_t804882D, 0x05);
		if ((int32) ((cmpResult_174 > 0x00) - (cmpResult_174 < 0x00)) == 0x00)
		{
			if (auth->dw0020 != 0x00)
				system("/bin/sh");
			else
				fwrite(&g_v804883B, 0x01, 0x0A, stdout);
		}
	}
}

// 08048740: void __libc_csu_init(Stack word32 dwArg04, Stack word32 dwArg08, Stack word32 dwArg0C)
void __libc_csu_init(word32 dwArg04, word32 dwArg08, word32 dwArg0C)
{
	_init();
	int32 edi_29 = &g_ptr804994C - &g_ptr804994C;
	if (edi_29 >> 0x02 != 0x00)
	{
		int32 esi_39 = 0x00;
		do
		{
			(*((char *) &g_ptr804994C + esi_39 * 0x04))();
			++esi_39;
		} while (esi_39 != edi_29 >> 0x02);
	}
}

// 080487B0: void __libc_csu_fini()
void __libc_csu_fini()
{
}

// 080487B2: void __i686.get_pc_thunk.bx()
void __i686.get_pc_thunk.bx()
{
}

// 080487C0: void __do_global_ctors_aux()
// Called from:
//      _init
void __do_global_ctors_aux()
{
	<anonymous> * eax_12 = g_ptr804994C;
	if (eax_12 != (<anonymous> *) ~0x00)
	{
		word32 * ebx_15 = &g_ptr804994C;
		do
		{
			eax_12();
			ebx_15 -= 0x04;
			eax_12 = *ebx_15;
		} while (eax_12 != (<anonymous> *) ~0x00);
	}
}

// tmp0vrim1_3_bss.c
// Generated by decompiling tmp0vrim1_3
// using Reko decompiler version 0.11.6.0.

#include "tmp0vrim1_3.h"

FILE * stdin = &g_t10093500; // 08049A80
FILE * stdout = &g_t10093540; // 08049AA0
byte g_b8049AA4 = 0x00; // 08049AA4
uint32 dtor_idx.6161 = 0x00; // 08049AA8
struct Eq_80 * auth = null; // 08049AAC
char * service = null; // 08049AB0
// tmp0vrim1_3_ctors.c
// Generated by decompiling tmp0vrim1_3
// using Reko decompiler version 0.11.6.0.

#include "tmp0vrim1_3.h"

<anonymous> * g_ptr804994C = &g_tFFFFFFFF; // 0804994C
// tmp0vrim1_3_fini.c
// Generated by decompiling tmp0vrim1_3
// using Reko decompiler version 0.11.6.0.

#include "tmp0vrim1_3.h"

// 080487EC: void _fini()
void _fini()
{
	__do_global_dtors_aux();
}

// tmp0vrim1_3_dtors.c
// Generated by decompiling tmp0vrim1_3
// using Reko decompiler version 0.11.6.0.

#include "tmp0vrim1_3.h"

<anonymous> * g_a8049954[] = // 08049954
	{
	};
// tmp0vrim1_3_rodata.c
// Generated by decompiling tmp0vrim1_3
// using Reko decompiler version 0.11.6.0.

#include "tmp0vrim1_3.h"

word32 _fp_hw = 0x03; // 08048808
word32 _IO_stdin_used = 0x00020001; // 0804880C
char g_str8048810[] = "%p, %p \n"; // 08048810
Eq_104 g_t8048819 = // 08048819;
Eq_122 g_t804881F = // 0804881F;
Eq_172 g_t8048825 = // 08048825;
Eq_195 g_t804882D = // 0804882D;
char g_str8048833[] = "/bin/sh"; // 08048833
void g_v804883B = ??void??; // 0804883B
// tmp0vrim1_3_jcr.c
// Generated by decompiling tmp0vrim1_3
// using Reko decompiler version 0.11.6.0.

#include "tmp0vrim1_3.h"

word32 g_dw804995C = 0x00; // 0804995C
// tmp0vrim1_3_got.c
// Generated by decompiling tmp0vrim1_3
// using Reko decompiler version 0.11.6.0.

#include "tmp0vrim1_3.h"

word32 g_dw8049A28 = 0x00; // 08049A28
// tmp0vrim1_3_init.c
// Generated by decompiling tmp0vrim1_3
// using Reko decompiler version 0.11.6.0.

#include "tmp0vrim1_3.h"

// 080483C4: void _init()
// Called from:
//      __libc_csu_init
void _init()
{
	if (g_dw8049A28 != 0x00)
		__gmon_start__();
	frame_dummy();
	__do_global_ctors_aux();
}

// tmp0vrim1_3_plt.c
// Generated by decompiling tmp0vrim1_3
// using Reko decompiler version 0.11.6.0.

#include "tmp0vrim1_3.h"

// 08048410: void printf()
void printf()
{
}

// 08048420: void free()
void free()
{
}

// 08048430: void strdup()
void strdup()
{
}

// 08048440: void fgets()
void fgets()
{
}

// 08048450: void fwrite()
void fwrite()
{
}

// 08048460: void strcpy()
void strcpy()
{
}

// 08048470: void malloc()
void malloc()
{
}

// 08048480: void system()
void system()
{
}

// 08048490: void __gmon_start__()
void __gmon_start__()
{
}

// 080484A0: void __libc_start_main()
void __libc_start_main()
{
}

