#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#define _GNU_SOURCE
#include <unistd.h>

int main(int argc, char **argv) {
    if (atoi(argv[1]) != 423)
        fwrite("No !", 1, 5, stderr);
    else {
        char* shell = strdup("/bin/sh");
        int gid = getegid(); //effective group id of the calling process
        int uid = geteuid(); //effective user id of the calling process
        setresgid(gid, gid, gid); //set the real gid, effective gid and sugid of the process
        setresuid(uid, uid, uid); //set the real uid, effective uid and suuid of the process
        execv("/bin/sh", (char*[2]){shell, NULL}); //note: the args of execv where generated by stack manipulation in the decompiled code (see esp manipulations in the gdb dump, 0x08048eec <+44>:    mov    %eax,0x10(%esp)
                                                                                                                                                                                //0x08048ef0 <+48>:    movl   $0x0,0x14(%esp)
    }
    return 0;
}